# fly.toml app configuration file generated for fit-flow-users on 2025-08-17T07:35:35-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fit-flow-users'
primary_region = 'ord'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
